# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
name: categorie
services:
  postgresql:
    image: postgres:16.4
    # volumes:
    #   - ~/volumes/jhipster/categorie/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=categorie
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432

  backend:
    build: ./backend
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/categorie
      - SPRING_DATASOURCE_USERNAME=categorie
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=prod,api-docs
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080

  frontend:
    build: ./frontend
    depends_on:
      - backend
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:4200:80

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: ['start-dev']
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresql:5432/keycloak
      - KC_DB_USERNAME=categorie
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgresql
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9080:8080